OnlineStore/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using OnlineStore.Data;
using Microsoft.EntityFrameworkCore;
using OnlineStore.Models.Entities;

namespace OnlineStore.Controllers
{
    public class NewsController : Controller
    {
        private readonly ApplicationDbContext _context;

        public NewsController(ApplicationDbContext context)
        {
            _context = context;
        }

        public async Task<IActionResult> Index()
        {
            return View(await _context.News.ToListAsync());
        }

        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .SingleOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Title,ShortText,Text")] News news)
        {
            if (ModelState.IsValid)
            {
                news.CreatedDate = DateTime.Now;
                _context.Add(news);
                await _context.SaveChangesAsync();
                return RedirectToAction("Index");
            }
            return View(news);
        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News.SingleOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }
            return View(news);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
   public async Task<IActionResult> Edit(int id, [Bind("Id,Title,ShortText,Text")] News news)
        {
            if (id != news.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(news);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!NewsExists(news.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction("Index");
            }
            return View(news);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var news = await _context.News
                .SingleOrDefaultAsync(m => m.Id == id);
            if (news == null)
            {
                return NotFound();
            }

            return View(news);
        }

        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var news = await _context.News.SingleOrDefaultAsync(m => m.Id == id);
            _context.News.Remove(news);
            await _context.SaveChangesAsync();
            return RedirectToAction("Index");
        }

        private bool NewsExists(int id)
        {
            return _context.News.Any(e => e.Id == id);
        }
    }
}

OnlineStore/Controllers/TestController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.Extensions.Configuration;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using OnlineStore.Data;
using OnlineStore.Models.Test;
using OnlineStore.Models.Entities;
using Microsoft.EntityFrameworkCore;
using OnlineStore.Services;

namespace OnlineStore.Controllers
{
    public class TestController : Controller
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly SignInManager<ApplicationUser> _signInManager;
        private readonly ILogger _logger;
        private readonly ApplicationDbContext _context;
        private readonly IEmailSender _emailSender;

        public TestController(
            UserManager<ApplicationUser> userManager,
            SignInManager<ApplicationUser> signInManager,
            ApplicationDbContext context,
            ILoggerFactory loggerFactory,
              IEmailSender emailSender)
        {
            _userManager = userManager;
            _signInManager = signInManager;
            _logger = loggerFactory.CreateLogger<AccountController>();
            _context = context;
            _emailSender = emailSender;
        }

        public async Task<IActionResult> Index()
        {
            return RedirectToAction("Users");
        }

        public async Task<IActionResult> Users()
        {
            return View();
        }

        public async Task<IActionResult> EditFollowers()
        {
            var userNames = _context.Users.Select(u => u.UserName);
            ViewBag.UserNames = new SelectList(userNames);
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> EditFollowers(TestRegister form)
        {
            if (form.follower == form.follows)
            {
                var userNames = _context.Users.Select(u => u.UserName);
                ViewBag.UserNames = new SelectList(userNames);
                ModelState.AddModelError("", "Нельзя прикреплять самого на себя");
                return View(form);
            }

            var followerUser = _context.Users.FirstOrDefault(u => u.UserName == form.follower);
            var follower = _context.Followers.FirstOrDefault(f => f.UserId == followerUser.Id);

            var newParentUser = _context.Users.FirstOrDefault(u => u.UserName == form.follows);
            var newParentFollower = _context.Followers.FirstOrDefault(f => f.UserId == newParentUser.Id);

            if (newParentFollower == null)
            {
                newParentFollower = new Follower { UserId = newParentUser.Id };
                _context.Followers.Add(newParentFollower);
                _context.SaveChanges();
            }
            else if (follower != null && newParentFollower.ParentId == follower.FollowerId)
            {
                newParentFollower.ParentId = null;
                _context.SaveChanges();
            }

            if (follower == null)
            {
                follower = new Follower { UserId = followerUser.Id, ParentId = newParentFollower.FollowerId };
                _context.Followers.Add(follower);
            }
            else
            {
                follower.ParentId = newParentFollower.FollowerId;
            }

            _context.SaveChanges();

            ViewBag.ParentLogin = form.follows;
            ViewBag.FollowerLogin = form.follower;

            return View("EditFollowersSuccess");
        }



        [HttpPost]
        public async Task<IActionResult> Register(string login)
        {
            var user = new ApplicationUser { UserName = login, Email = login + "@test.ru" };
            var result = await _userManager.CreateAsync(user, "Qwerty##45");
            if (result.Succeeded)
            {

                await _signInManager.SignInAsync(user, isPersistent: false);
                _logger.LogInformation(3, "User created a new account with password.");
            }

            ViewBag.NewUserLogin = login;

            return View("RegisterSuccess");
        }

        public async Task<IActionResult> Buying()
        {
            var userNames = _context.Users.Select(u => u.UserName);
            ViewBag.UserNames = new SelectList(userNames);
            var products = _context.Products.Select(p => new
            {
                Id = p.Id,
                Value = $"{p.Name}, цена {p.Price}, для начислений {p.AmountToDistribution}"
            }).ToList();
            ViewBag.Products = new SelectList(products, "Id", "Value");
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Buying(string login, int productId)
        {
            var product = await _context.Products.FindAsync(productId);
            var AmountToAccruals = product.AmountToDistribution / 6;

            var usersReceivedAccruals = new List<string>();
            var user = _context.Users.FirstOrDefault(u => u.UserName == login);

            var order = new Order { User = user,Datetime = DateTime.Now };

            _context.Orders.Add(order);
            _context.SaveChanges();

            var orderProducts = new OrderProduct { Order = order, Product = product };
            _context.OrderProducts.Add(orderProducts);
            _context.SaveChanges();


            ChargeAccrual(usersReceivedAccruals, user, 1, AmountToAccruals, order);
            _context.SaveChanges();

            // create transaction to PremiumFund
            var membersAccrualsSum = _context.Transactions.Where(t => t.OrderId == order.Id).Sum(t => t.Amount);
            var premiumFundUser = _context.Users.FirstOrDefault(u => u.UserName == "PremiumFund");

            var fundTransaction = new Transaction
            {
                RecipientId = premiumFundUser.Id,
                Amount = product.AmountToDistribution - membersAccrualsSum,
                Datetime = DateTime.Now,
                TransactionTypeId = "02",
                Order = order
            };
            _context.Transactions.Add(fundTransaction);
            _context.SaveChanges();

            ViewBag.UserNames = usersReceivedAccruals;
            return View("BuyingSuccess");
        }

        private void ChargeAccrual(List<string> usersReceivedAccruals, ApplicationUser user, int layer, int amountToAccruals, Order order)
        {
            var parentFollowerId = _context.Followers.FirstOrDefault(f => f.UserId == user.Id)?.ParentId;
            if (parentFollowerId != null)
            {
                var parentFollower = _context.Followers.FirstOrDefault(f => f.FollowerId == parentFollowerId);
                var parentUser = _context.Users.FirstOrDefault(u2 => u2.Id == parentFollower.UserId);

                var transaction = new Transaction
                {
                    RecipientId = parentUser.Id,
                    Amount = amountToAccruals,
                    Datetime = DateTime.Now,
                    TransactionTypeId = "02",
                    Order = order
                };

                _context.Transactions.Add(transaction);
                usersReceivedAccruals.Add(parentUser.UserName);

                if (layer < 5)
                {
                    layer++;
                    ChargeAccrual(usersReceivedAccruals, parentUser, layer, amountToAccruals, order);
                }
            }
        }

        public async Task<IActionResult> Followers()
        {
            var users = _context.Users.ToList();
            var followers = _context.Followers.ToList();
            var result = new List<TestFollower>();

            foreach (var u in users)
            {
                var parentFollowerId = followers.FirstOrDefault(f => f.UserId == u.Id)?.ParentId;
                if (parentFollowerId != null)
                {
                    var parentFollower = followers.FirstOrDefault(f => f.FollowerId == parentFollowerId);
                    var parentUserName = users.FirstOrDefault(u2 => u2.Id == parentFollower.UserId).UserName;
                    result.Add(new TestFollower { Name = u.UserName, ParentName = parentUserName });
                }
                else
                {
                    result.Add(new TestFollower { Name = u.UserName });
                }
            };

            return View(result);
        }

        public async Task<IActionResult> Balances()
        {
            var users = _context.Users.ToList();
            var transactions = _context.Transactions.ToList();
            var result = new List<TestBalance>();

            foreach (var u in users)
            {
                var userBalance = transactions.Where(t => t.RecipientId == u.Id).ToList().Sum(t => t.Amount);

                result.Add(new TestBalance { Name = u.UserName, Amount = userBalance });
            };

            return View(result);
        }

        public async Task<IActionResult> Hierarchy()
        {
            var users = _context.Users.ToList();
            var followers = _context.Followers.OrderBy(f => f.ParentId).ToList();
            var followersNames = new List<TestFollower>();

            var fisrtFollower = followers.FirstOrDefault(f => f.ParentId == null);
            var firstUser = users.FirstOrDefault(u => u.Id == fisrtFollower?.UserId);

            var result = new TestHierarchy { Name = firstUser.UserName };

            while (followers.Count > 0)
            {

            }




            foreach (var u in users)
            {
                var parentFollowerId = followers.FirstOrDefault(f => f.UserId == u.Id)?.ParentId;
                if (parentFollowerId != null)
                {
                    var parentFollower = followers.FirstOrDefault(f => f.FollowerId == parentFollowerId);

OnlineStore/Views/Shared/_EmtptyTempLayout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>

    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                </ul>
                @await Html.PartialAsync("_LoginPartialTemp")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />

    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

OnlineStore/Views/Shared/_Layout.cshtml
@inject Microsoft.ApplicationInsights.AspNetCore.JavaScriptSnippet JavaScriptSnippet
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
    @Html.Raw(JavaScriptSnippet.FullScript)
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">OnlineStore</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Products">Products</a></li>
                </ul>
                @await Html.PartialAsync("_LoginPartial")
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2017 - OnlineStore</p>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

OnlineStore/Views/Shared/_LoginPartialTemp.cshtml
@using OnlineStore.Models.Entities

@inject SignInManager<ApplicationUser> SignInManager
@inject UserManager<ApplicationUser> UserManager

@if (SignInManager.IsSignedIn(User))
{
    <form asp-area="" asp-controller="Account" asp-action="Logout" method="post" id="logoutForm" class="navbar-right">
        <ul class="nav navbar-nav navbar-right">
            <li>
                <button type="submit" class="btn btn-link navbar-btn navbar-link">Выход</button>
            </li>
        </ul>
    </form>
}
else
{

}

OnlineStore/Views/Shared/_TestLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - OnlineStore</title>

    <environment names="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
        <script src="~/lib/jquery/dist/jquery.min.js"></script>

    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">.</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Test" asp-action="Users">Регистрация пользователя</a></li>
                    <li><a asp-area="" asp-controller="Test" asp-action="Followers">Пользователи</a></li>
                    <li><a asp-area="" asp-controller="Test" asp-action="EditFollowers">Прикрепления</a></li>
                    <li><a asp-area="" asp-controller="Test" asp-action="Balances">Начисления</a></li>
                    <li><a asp-area="" asp-controller="Test" asp-action="Buying">Имитация покупок</a></li>
                    <li><a asp-area="" asp-controller="Test" asp-action="EditDefaultUserToFollow">Ст. подписка</a></li>
                    <li><a asp-area="" asp-controller="Test" asp-action="ReferralNetworkCandidates">Реф. сеть</a></li>
                    <li><a asp-area="" asp-controller="Products" asp-action="Index">Товары</a></li>
                    <li><a asp-area="" asp-controller="News" asp-action="Index">Новости</a></li>
                </ul>
                
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
        </footer>
    </div>

    <environment names="Development">
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment names="Staging,Production">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.6/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("scripts", required: false)
</body>
</html>

OnlineStore/Views/Shared/_TopBarPartial.cshtml
@{
    var topMenu = (ViewData["TopMenu"]!=null ? (int)ViewData["TopMenu"]:0 );
}
<div id="top-bar" class="top-bar--style-1">
    <div class="container">
        <a id="top-bar__logo" class="site-logo" href="/">AGRICOM</a>

        <a id="top-bar__navigation-toggler" href="javascript:void(0);"><span></span></a>

        <nav id="top-bar__navigation" role="navigation">
            <ul>
                <li class="@(topMenu == (int)OnlineStore.Utils.Enum.TopMenuEnum.Home?"current":"")"  >
                    <a href="@Url.Action("Index","Home")">Главная</a>

                    <div class="submenu">
                        <ul>
                            <li class="current"><a href="/">Home Style 1</a></li>
                            <li><a href="/" target="_blank">Home Style 2</a></li>
                            <li><a href="/" target="_blank">One Page</a></li>
                        </ul>
                    </div>
                </li>
                <li  class="@(topMenu == (int)OnlineStore.Utils.Enum.TopMenuEnum.News?"current":"")" ><a href="@Url.Action("News","Home")">Новости</a></li>
                <li>
                    <a href="javascript:void(0);">О сливе</a>

                    <div class="submenu">
                        <ul>
                            <li><a href="about.html">about</a></li>
                            <li><a href="products.html">products</a></li>
                            <li><a href="product_case.html">product case</a></li>
                            <li><a href="404.html">404 page</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="javascript:void(0);">О нас</a>

                    <div class="submenu">
                        <ul>
                            <li><a href="about.html">about</a></li>
                            <li><a href="products.html">products</a></li>
                            <li><a href="product_case.html">product case</a></li>
                            <li><a href="404.html">404 page</a></li>
                        </ul>
                    </div>
                </li>
                <li>
                    <a href="javascript:void(0);">Еще товары</a>

                    <div class="submenu">
                        <ul>
                            <li><a href="gallery_1.html">2 Columns</a></li>
                            <li><a href="gallery_2.html">3 Columns</a></li>
                            <li><a href="gallery_3.html">4 Columns</a></li>
                            <li><a href="gallery_4.html">Masonry</a></li>
                            <li><a href="gallery_5.html">Masonry 2</a></li>
                        </ul>
                    </div>
                </li>
              
                <li><a href="contacts.html">Контакты</a></li>
                <li class="li-btn">
                    @if (User.Identity.IsAuthenticated)
                    {
                        <a class="custom-btn primary" href="/referral">Партнерка</a>
                    }
                    else
                    {
                        <a class="custom-btn primary" href="/a/register">Регистрация</a>
                    }

                </li>
            </ul>
        </nav>
    </div>
</div>